# Generated by Django 5.2.10 on 2026-03-03 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('draft_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('content_type', models.CharField(default='instagram_post', max_length=64)),
                ('tone', models.CharField(default='casual', max_length=32)),
                ('status', models.CharField(default='generated', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('lang', models.CharField(default='en', max_length=12)),
                ('text', models.TextField()),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='generated', max_length=32)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='frontend_app.draft')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=64)),
                ('publish_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='scheduled', max_length=32)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_app.draft')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_app.variant')),
            ],
        ),
    ]
